# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v8j1jG0MPqQAaC_0gIkY5fGOxoMhLZaw
"""

from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
@app.route("/home")
def homepage():
    return render_template('home.html')

@app.route("/about")
def aboutpage():
    return render_template('about.html')

@app.route("/signin")
def signinpage():
    return render_template('signin.html')

@app.route("/signup")
def signuppage():
    return render_template('signup.html')